language: python
python:
    - "3.8"

services:
    - docker

before_scripts: 
    - docker-compose up   -d
    - docker ps
    - docker pip install flake8


scripts:
    - docker-compose run app python manage.py test 
